config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'

  resources :preferences

  devise_for :users
  get 'landing/set_preferences' => 'landing#set_preferences', :as => :set_preferences
  root 'landing#index', :as => :index_preferences

end

app/models/user.rb
class User < ActiveRecord::Base
	  mount_uploader :image, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  	@time = ['morning','afternoon','evening']
  	if params[:pid]
	  	if params[:toggle]
	  		preference = current_user.preferences.find(params[:pid])
	  		if preference.enable == 1
	  			preference_order = Preference.where(:text=>nil)
	  			preference_order.each do |f|
	  				if f.order < preference.order and f.enable==1
	  					f.order+=1
	  					f.save!
	  				end
	  			end
	  			preference.enable = 0
	  			preference.order = -1
	  		else
	  			preference_order = Preference.where(:text=>nil)
	  			preference_order.each do |f|
	  				if f.enable==1 and f.order==0
	  					f.order+=1
	  					f.save!
	  				end
	  			end
	  			preference_order_first = Preference.where(:text=>nil).order(:order)
	  			preference_order_first.each do |f|
	  				if f.order>0
	 					preference.enable = 1
	  					preference.order = f.order - 1
	  					break
	  				end
	  			end
	  		end
	  	preference.save!
	  	end

	  	if params[:op]
	  		preference = current_user.preferences.find(params[:pid])
	  		if params[:op].to_i==1
	  			select_preference = current_user.preferences.where(order: preference.order+1).first
	  			select_preference.order-=1 
	  			preference.order+=1
	  		else
	  			select_preference = current_user.preferences.where(order: preference.order-1).first
	  			select_preference.order+=1
	  			preference.order-=1
	  		end
	  		preference.save!
	  		select_preference.save!
	  	end
	  	redirect_to index_preferences_path
	  end

  	if current_user.preferences.exists?
    @preferences = current_user.preferences.where(:text=>nil).order(order: :desc)
    else
    Preference.create!(:name=>"WhatsApp",:order=>1,:enable=>1,:user_id=>current_user.id)
    Preference.create!(:name=>"Text Messages",:order=>2,:enable=>1,:user_id=>current_user.id)
    Preference.create!(:name=>"Email",:order=>3,:enable=>1,:user_id=>current_user.id)
    Preference.create!(:name=>"Phone Calls",:order=>0,:enable=>1,:user_id=>current_user.id)
    Preference.create!(:name=> "Saturday",:user_id=>current_user.id,:text=>"")
    Preference.create!(:name=> "Weekdays",:user_id=>current_user.id,:text=>"")
    Preference.create!(:name=> "Sunday",:user_id=>current_user.id,:text=>"")
    @preferences = current_user.preferences.where(:text=>nil).order(order: :desc)
  end
  	@weekdays = current_user.preferences.where(:name=>"Weekdays").first
	@weekdays = @weekdays.text.split(',')
	@saturday = current_user.preferences.where(:name=>"Saturday").first
	@saturday = @saturday.text.split(',')
	@sunday = current_user.preferences.where(:name=>"Sunday").first
	@sunday = @sunday.text.split(',')
  end
	respond_to do |format|
		format.html
		format.js
	end


def set_preferences
		# puts "Weekdays:  " + params[:wday_1].to_s + ","+ params[:wday_2].to_s + "," + params[:wday_3].to_s+ "================================================================================"
		preference1 = current_user.preferences.where(:name=>"Weekdays").first
		# puts preference.to_s + "11111111111111111111111111111111111111111111".to_s
		preference1.text = params[:wday_1].to_s + ","+ params[:wday_2].to_s + "," + params[:wday_3].to_s
		preference1.save!
		# puts "Saturday:  " + params[:stday_1].to_s + ","+ params[:stday_2].to_s + "," + params[:stday_3].to_s+ "==================================================================================================================================================================\n\n\n\n\n\n"
		preference2 = current_user.preferences.where(:name=>"Saturday").first
		# puts "8888888888888888888888888"
		preference2.text = params[:stday_1].to_s + ","+ params[:stday_2].to_s + "," + params[:stday_3].to_s
		# puts "66666666666666666666666666"
		preference2.save!
		# puts "Sunday:    " + params[:suday_1].to_s + ","+ params[:suday_2].to_s + "," + params[:suday_3].to_s+ "================================================================================"
		preference3 = current_user.preferences.where(:name=>"Sunday").first
		preference3.text = params[:suday_1].to_s + ","+ params[:suday_2].to_s + "," + params[:suday_3].to_s
		preference3.save!
		redirect_to index_preferences_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/landing/_preference.html.erb
                    <div class="row">
                        <div class="col-md-12">
                            <ul class="timeline">
                            <% @preferences.each do |f|%>
                                <li>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header no-border" style="text-align:center;">
                                        <div class="row">
                                            <% if f.enable == 1 %>
                                                <div class="col-md-4">
                                        				<% if f.order!=3 %>
                                        					<a href="./landing/index?op=1&pid=<%=f.id%>" class="up_arrow_box" data-remote="true">
                                        					</a>
                                        				<% end %>
	                                        	<% if f.order!=0 %>
	                                        		<a href="./landing/index?op=0&pid=<%=f.id%>" style="margin-left:10px" class="down_arrow_box" data-remote="true">
	                                        		</a>
	                                        	<% end %>
                                                </div>
                                                <div class="col-md-4">
                                                    <div style="display:inline"><%= f.name %></div>
                                                    </div>
                                            <div class="col-md-4">
                                			<%= link_to ' Disable?', index_preferences_path(:toggle => 1, :pid => f.id),:remote => true,:class=>"enable" %>        
                                            </div>
                                        	<% else %>
                                            <div class="col-md-4 col-md-offset-4">
                                        	   <div style="text-decoration:line-through;display:inline;color:#D0D0D0"><%= f.name %></div>
                                               </div>
                                            <div class="col-md-4">
                                        	<%= link_to ' Enable?', index_preferences_path(:toggle => 1, :pid => f.id),:remote => true,:class=>"enable" %>
                                            </div>
                                        	<% end %> <br>
                                            </div>
                                        </h3>
                                    </div>
                                </li>
                                <% end %>
                            </ul>
                        </div><!-- /.col -->
                    </div><!-- /.row -->

app/views/landing/index.html.erb
<!DOCTYPE html>
<html style="min-height: 1843px;"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="UTF-8">
        <title>Preferences</title>
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <link href="./AdminLTE   Timeline_files/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="./AdminLTE   Timeline_files/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="./AdminLTE   Timeline_files/ionicons.min.css" rel="stylesheet" type="text/css">
        <link href="./AdminLTE   Timeline_files/AdminLTE.css" rel="stylesheet" type="text/css">

    </head>
    <body class="skin-blue  pace-done" style="min-height: 1843px;"><div class="pace  pace-inactive"><div class="pace-progress" data-progress-text="100%" data-progress="99" style="width: 100%;">
  <div class="pace-progress-inner"></div>
</div>
<div class="pace-activity"></div></div>
        <div class="wrapper row-offcanvas row-offcanvas-left" style="min-height: 633px;">
                <section class="content-header">
                    <h3 style="text-align:center">
 						Hi user! Here are your preferences <br>
                     <small>Click the arrows to set the order of your preferences</small>
                     </h3>

                </section>
                <section class="content">
                	<div id ="preferences">
						<%= render('preference') %>
					</div>
                </section>
                <section class="content">
                    <div class="row">
                        <% params[:wday_1] = "" %>
                        <% params[:wday_2] = "" %>
                        <% params[:wday_3] = "" %>
                        <% params[:stday_1] = "" %>
                        <% params[:stday_2] = "" %>                        
                        <% params[:stday_3] = "" %>
                        <% params[:suday_1] = "" %>                        
                        <% params[:suday_2] = "" %>                        
                        <% params[:suday_3] = "" %>
                        <% flag_weekdays = 0 %>
                        <% flag_saturdays = 0 %>
                        <% flag_sundays = 0 %>
                        <% @time.each do |t| %>
                                <% if @weekdays.include?(t.to_s) %>
                                    <% flag_weekdays = 1 %>
                                <% end %>
                                <% if @sunday.include?(t.to_s) %>
                                    <% flag_sundays = 1 %>
                                <% end %>
                                <% if @saturday.include?(t.to_s) %>
                                    <% flag_saturdays = 1 %>
                            <% end %>
                        <% end %>
                        <div class="col-md-12">
                            <ul class="timeline">
                                <li>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header no-border" style="text-align:center;">
                                            <% if flag_weekdays == 1 or flag_saturdays == 1 or flag_sundays == 1 %>
                                                <p style="text-align:center"> Currently,</p>
                                            <% end %>
                                                <% if flag_weekdays == 1 %>
                                                    <p> You prefer to play in the
                                                    <% @weekdays.each do |f| %>
                                                    <% if f != "" %>
                                                      <strong> <%= f %>s </strong>,
                                                    <% end %>
                                                    <% end %>
                                                    in the weekdays </p>
                                                <% end %>
                                                <% if flag_saturdays == 1 %>
                                                    <p> You prefer to play in the
                                                    <% @saturday.each do |f| %>
                                                    <% if f != "" %>
                                                      <strong> <%= f %>s </strong>,
                                                    <% end %>
                                                    <% end %>
                                                    on Saturdays </p>
                                                <% end %>
                                                 <% if flag_sundays == 1 %>
                                                    <p> You prefer to play in the
                                                    <% @sunday.each do |f| %>
                                                    <% if f != "" %>
                                                      <strong> <%= f %>s </strong>,
                                                    <% end %>
                                                    <% end %>
                                                    on Sundays </p>
                                                <% end %>
                                                    <br/>
                                                    <br/>
                                            <div class="row">
                                                <div class="col-md-4">
                                                <h4> On weekdays, I am available: </h4>
                                                <%= form_tag(set_preferences_path,:method => "get") do %>
                                                    <%= check_box_tag :wday_1,"morning",false,:wday_1 => params[:wday_1] %> In the morning <p></p>
                                                    <%= check_box_tag :wday_2,"afternoon",false,:wday_2 => params[:wday_2] %> In the afternoon <p></p>
                                                    <%= check_box_tag :wday_3,"evening",false,:wday_3 => params[:wday_3] %> In the evening <p></p>       
                                                </div>
                                                <div class="col-md-4">
                                                <h4> On Saturdays, I am available: </h4>
                                                    <%= check_box_tag :stday_1,"morning",false,:stday_1 => params[:stday_1] %> In the morning <p></p>
                                                    <%= check_box_tag :stday_2,"afternoon",false,:stday_2 => params[:stday_2] %> In the afternoon <p></p>
                                                    <%= check_box_tag :stday_3,"evening",false,:stday_3 => params[:stday_3] %> In the evening <p></p>       
                                                </div>

                                                <div class="col-md-4">
                                                <h4> On Sundays, I am available: </h4>
                                                    <%= check_box_tag :suday_1,"morning",false,:suday_1 => params[:suday_1] %> In the morning <p></p>
                                                    <%= check_box_tag :suday_2,"afternoon",false,:suday_2 => params[:suday_2] %> In the afternoon <p></p>
                                                    <%= check_box_tag :suday_3,"evening",false,:suday_3 => params[:suday_3] %> In the evening <p></p>       
                                                </div>
                                            </div>
                                            <br/>
                                            <br/>

                                            <div style="text-align:center">
                                                <%= submit_tag "Submit" %>
                                                    <% end %>
                                            </div>
                                        </h3>
                                    </div>
                                </li>
                            </ul>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </section>
            </div>
        <script src="./AdminLTE   Timeline_files/jquery.min.js"></script>
        <script src="./AdminLTE   Timeline_files/bootstrap.min.js" type="text/javascript"></script>
        <!-- AdminLTE App -->
        <script src="./AdminLTE   Timeline_files/app.js" type="text/javascript"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="./AdminLTE   Timeline_files/demo.js" type="text/javascript"></script>
    
</body></html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RLpreferences</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
<%= link_to 'LOGOUT', destroy_user_session_path, :method => :delete %> <br>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.image %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag (@user.image), size: '400x500' %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>